services:
  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products_api_production
    ports:
      - "5432:5432"

  products_api:
    build:
      context: ./products_api
    env_file:
      - ./products_api/.env.exemple
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/products_api_development
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./products_api:/rails
    command: sh -c "bundle exec rails db:seed && bundle exec rails server -b 0.0.0.0 -p 3000"

  product-frontend:
    build:
      context: ./product-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./product-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    command: npm run dev -- --host

volumes:
  db_data:
